-- Seed data for CuisineStyle
INSERT INTO "CuisineStyle" ("Name", "Emoji") VALUES
('Italian', '🇮🇹'),
('Mexican', '🇲🇽'),
('Japanese', '🇯🇵'),
('Chinese', '🇨🇳'),
('Indian', '🇮🇳'),
('French', '🇫🇷'),
('Thai', '🇹🇭'),
('Greek', '🇬🇷'),
('Spanish', '🇪🇸'),
('Korean', '🇰🇷'),
('Vietnamese', '🇻🇳'),
('Turkish', '🇹🇷'),
('Lebanese', '🇱🇧'),
('Moroccan', '🇲🇦'),
('Brazilian', '🇧🇷'),
('Ethiopian', '🇪🇹'),
('Caribbean', '🇯🇲'),
('American', '🇺🇸'),
('German', '🇩🇪'),
('British', '🇬🇧'),
('Peruvian', '🇵🇪'),
('Indonesian', '🇮🇩'),
('Filipino', '🇵🇭'),
('Mediterranean', '🌊'),
('Middle Eastern', '🥙'),
('Nordic', '🇸🇪'),
('Cajun/Creole', '🥘'),
('Portuguese', '🇵🇹'),
('Russian', '🇷🇺'),
('Persian', '🇮🇷');
